modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issue_tracker}"
# Keep the built-in textures active by default; NeoForge ignores pack.mcmeta's default flags.
showAsResourcePack=false

[[mods]]
modId="chickens"
version="${mod_version}"
displayName="${mod_display_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.chickens]]
modId="neoforge"
mandatory=true
versionRange="[21.1.0,)"
ordering="NONE"
sides="BOTH"

[[dependencies.chickens]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
sides="BOTH"

[[dependencies.chickens]]
modId="kubejs"
mandatory=false
versionRange="[2101.7.2-build.336,)"
ordering="AFTER"
sides="BOTH"
